# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-assemblybacterias-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::python-wget=3.2

  # TODO nf-core: Add required software dependencies here

  - bioconda::fastqc=0.11.8
  - bioconda::quast=5.0.2
  - bioconda::unicycler=0.4.8
  - bioconda::fastp=0.23.2
  - bioconda::multiqc=1.6
  - bioconda::prokka=1.14.6
  - bioconda::pilon=1.24
  - bioconda::spades=3.13.0
  
